trigger:
- main
- features/*

pool: new5
  

stages:
  - stage: 
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'service_connection5'
            backendAzureRmResourceGroupName: 'rg5'
            backendAzureRmStorageAccountName: 'stg984'
            backendAzureRmContainerName: 'container5'
            backendAzureRmKey: 'ranjeet.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            
  # - stage: 
  #   jobs:
  #     - job: 
  #       steps: 
  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
  #           backendServiceArm: 'interview_connection'
  #           backendAzureRmResourceGroupName: 'rg7'
  #           backendAzureRmStorageAccountName: 'teststg78'
  #           backendAzureRmContainerName: 'tfstatecontainer'
  #           backendAzureRmKey: 'ranjeet.tfstate'
