trigger:
- main
- features/*

pool: asr_pool
  

stages:
  - stage: 
    jobs:
      - job: 
        steps:
        # - task: TerraformInstaller@1
        #   inputs:
        #     terraformVersion: 'latest'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            backendServiceArm: 'interview_connection'
            backendAzureRmOverrideSubscriptionID: '9246877f-9bea-4e72-9d6d-6b6d49d180df'
            backendAzureRmResourceGroupName: 'rg7'
            backendAzureRmStorageAccountName: 'teststg78'
            backendAzureRmContainerName: 'tfstatecontainer'
            backendAzureRmKey: 'ranjeet.tfstate'

        # - task: TerraformTask@5
        #   inputs:
        #     provider: 'azurerm'
        #     command: 'validate'
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
            
  # - stage: 
  #   jobs:
  #     - job: 
  #       steps: 
  #       - task: TerraformTask@5
  #         inputs:
  #           provider: 'azurerm'
  #           command: 'init'
  #           workingDirectory: '$(System.DefaultWorkingDirectory)/env/dev'
  #           backendServiceArm: 'interview_connection'
  #           backendAzureRmResourceGroupName: 'rg7'
  #           backendAzureRmStorageAccountName: 'teststg78'
  #           backendAzureRmContainerName: 'tfstatecontainer'
  #           backendAzureRmKey: 'ranjeet.tfstate'
